version: "2"

linters:
  default: "none"

  enable:
    - asciicheck
    - bidichk
    - containedctx
    - copyloopvar
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godoclint
    - godox
    - gosec
    - govet
    - iface
    - importas
    - inamedparam
    - ineffassign
    - intrange
    - iotamixing
    - ireturn
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - modernize
    - musttag
    - nestif
    - nilnesserr
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - sloglint
    - spancheck
    - staticcheck
    - tagalign
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - unqueryvet
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck

  settings:
    exhaustive:
      default-signifies-exhaustive: true

    revive:
      rules:
        - name: var-naming
          arguments:
            - []
            - []
            - - skip-package-name-collision-with-go-std: true

  exclusions:
    paths:
      - examples/do

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo

  settings:
    golines:
      max-len: 160
      tab-len: 4
      shorten-comments: true
      reformat-tags: false
      chain-split-dots: true
