// Command genmodules scans pkg/ for documentable modules and generates the
// list of NewDefaultConfig() calls consumed by cmd/docgen. A package qualifies
// when it declares both a package-level NewDefaultConfig function and a
// ConfigPath method on *Module — the same shape every built-in module's
// config/module pair has. This excludes pkg/config (whose ConfigPath lives on a
// generic bindModule), so no manual skip-list is needed.
package main

import (
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/mod/modfile"
)

const filePerm = 0o600

func main() {
	out := flag.String("o", "", "output file (default: stdout)")
	flag.Parse()

	root, err := findRepoRoot()
	if err != nil {
		fmt.Fprintln(os.Stderr, "genmodules:", err)
		os.Exit(1)
	}

	modPath, err := modulePath(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "genmodules:", err)
		os.Exit(1)
	}

	mods, err := discoverModules(filepath.Join(root, "pkg"), modPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "genmodules:", err)
		os.Exit(1)
	}

	src, err := render(mods)
	if err != nil {
		fmt.Fprintln(os.Stderr, "genmodules:", err)
		os.Exit(1)
	}

	if *out == "" {
		_, _ = os.Stdout.Write(src)
		return
	}

	if err := os.WriteFile(*out, src, filePerm); err != nil {
		fmt.Fprintln(os.Stderr, "genmodules:", err)
		os.Exit(1)
	}
}

type module struct {
	importPath string
	alias      string
}

// qualifies reports whether a package's parsed files describe a documentable
// module: a package-level NewDefaultConfig func plus a ConfigPath method on the
// concrete Module type.
func qualifies(files []*ast.File) bool {
	hasConfig := false
	hasConfigPath := false

	for _, f := range files {
		for _, decl := range f.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok {
				continue
			}

			if fn.Recv == nil {
				if fn.Name.Name == "NewDefaultConfig" {
					hasConfig = true
				}

				continue
			}

			if fn.Name.Name == "ConfigPath" && receiverIsModule(fn.Recv) {
				hasConfigPath = true
			}
		}
	}

	return hasConfig && hasConfigPath
}

func receiverIsModule(recv *ast.FieldList) bool {
	if recv == nil || len(recv.List) == 0 {
		return false
	}

	t := recv.List[0].Type
	if star, ok := t.(*ast.StarExpr); ok {
		t = star.X
	}

	id, ok := t.(*ast.Ident)

	return ok && id.Name == "Module"
}

func discoverModules(pkgRoot, modPath string) ([]module, error) {
	var dirs []string

	err := filepath.WalkDir(pkgRoot, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			dirs = append(dirs, path)
		}

		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk %s: %w", pkgRoot, err)
	}

	repoRoot := filepath.Dir(pkgRoot)

	var mods []module

	for _, dir := range dirs {
		fset := token.NewFileSet()

		pkgs, parseErr := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
			return !strings.HasSuffix(fi.Name(), "_test.go")
		}, 0)
		if parseErr != nil {
			return nil, fmt.Errorf("parse %s: %w", dir, parseErr)
		}

		for _, pkg := range pkgs {
			files := make([]*ast.File, 0, len(pkg.Files))
			for _, f := range pkg.Files {
				files = append(files, f)
			}

			if !qualifies(files) {
				continue
			}

			rel, relErr := filepath.Rel(repoRoot, dir)
			if relErr != nil {
				return nil, fmt.Errorf("rel %s: %w", dir, relErr)
			}

			rel = filepath.ToSlash(rel)
			mods = append(mods, module{
				importPath: modPath + "/" + rel,
				alias:      aliasFor(rel),
			})
		}
	}

	sort.Slice(mods, func(i, j int) bool { return mods[i].importPath < mods[j].importPath })

	return mods, nil
}

// aliasFor builds a collision-free import alias from a package's path relative
// to the repo root, e.g. "pkg/grpc/server" -> "pkg_grpc_server".
func aliasFor(rel string) string {
	var b strings.Builder

	for _, r := range rel {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}

	return b.String()
}

func render(mods []module) ([]byte, error) {
	var b strings.Builder

	b.WriteString("// Code generated by genmodules; DO NOT EDIT.\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")

	for _, m := range mods {
		fmt.Fprintf(&b, "\t%s %q\n", m.alias, m.importPath)
	}

	b.WriteString(")\n\n")
	b.WriteString("var defaultConfigs = []any{\n")

	for _, m := range mods {
		fmt.Fprintf(&b, "\t%s.NewDefaultConfig(),\n", m.alias)
	}

	b.WriteString("}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}

	return src, nil
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("getwd: %w", err)
	}

	for {
		if _, statErr := os.Stat(filepath.Join(dir, "go.mod")); statErr == nil {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("go.mod not found from working directory")
		}

		dir = parent
	}
}

func modulePath(root string) (string, error) {
	data, err := os.ReadFile(filepath.Join(root, "go.mod")) //nolint:gosec
	if err != nil {
		return "", fmt.Errorf("read go.mod: %w", err)
	}

	path := modfile.ModulePath(data)
	if path == "" {
		return "", errors.New("could not determine module path")
	}

	return path, nil
}
