// Code generated by genmodules; DO NOT EDIT.

package main

import (
	pkg_auth_verifier "github.com/Vilsol/lakta/pkg/auth/verifier"
	pkg_cache_memory "github.com/Vilsol/lakta/pkg/cache/memory"
	pkg_db_drivers_pgx "github.com/Vilsol/lakta/pkg/db/drivers/pgx"
	pkg_debug_actuator "github.com/Vilsol/lakta/pkg/debug/actuator"
	pkg_events_bus "github.com/Vilsol/lakta/pkg/events/bus"
	pkg_features_flags "github.com/Vilsol/lakta/pkg/features/flags"
	pkg_grpc_client "github.com/Vilsol/lakta/pkg/grpc/client"
	pkg_grpc_server "github.com/Vilsol/lakta/pkg/grpc/server"
	pkg_health "github.com/Vilsol/lakta/pkg/health"
	pkg_http_connect "github.com/Vilsol/lakta/pkg/http/connect"
	pkg_http_fiber "github.com/Vilsol/lakta/pkg/http/fiber"
	pkg_logging_slog "github.com/Vilsol/lakta/pkg/logging/slog"
	pkg_logging_tint "github.com/Vilsol/lakta/pkg/logging/tint"
	pkg_otel "github.com/Vilsol/lakta/pkg/otel"
	pkg_resilience_policy "github.com/Vilsol/lakta/pkg/resilience/policy"
	pkg_workers_pool "github.com/Vilsol/lakta/pkg/workers/pool"
	pkg_workers_scheduler "github.com/Vilsol/lakta/pkg/workers/scheduler"
	pkg_workflows_temporal "github.com/Vilsol/lakta/pkg/workflows/temporal"
)

var defaultConfigs = []any{
	pkg_auth_verifier.NewDefaultConfig(),
	pkg_cache_memory.NewDefaultConfig(),
	pkg_db_drivers_pgx.NewDefaultConfig(),
	pkg_debug_actuator.NewDefaultConfig(),
	pkg_events_bus.NewDefaultConfig(),
	pkg_features_flags.NewDefaultConfig(),
	pkg_grpc_client.NewDefaultConfig(),
	pkg_grpc_server.NewDefaultConfig(),
	pkg_health.NewDefaultConfig(),
	pkg_http_connect.NewDefaultConfig(),
	pkg_http_fiber.NewDefaultConfig(),
	pkg_logging_slog.NewDefaultConfig(),
	pkg_logging_tint.NewDefaultConfig(),
	pkg_otel.NewDefaultConfig(),
	pkg_resilience_policy.NewDefaultConfig(),
	pkg_workers_pool.NewDefaultConfig(),
	pkg_workers_scheduler.NewDefaultConfig(),
	pkg_workflows_temporal.NewDefaultConfig(),
}
