// Code generated by genmodules; DO NOT EDIT.

package main

import (
	pkg_db_drivers_pgx "github.com/Vilsol/lakta/pkg/db/drivers/pgx"
	pkg_grpc_client "github.com/Vilsol/lakta/pkg/grpc/client"
	pkg_grpc_server "github.com/Vilsol/lakta/pkg/grpc/server"
	pkg_health "github.com/Vilsol/lakta/pkg/health"
	pkg_http_fiber "github.com/Vilsol/lakta/pkg/http/fiber"
	pkg_logging_slog "github.com/Vilsol/lakta/pkg/logging/slog"
	pkg_logging_tint "github.com/Vilsol/lakta/pkg/logging/tint"
	pkg_otel "github.com/Vilsol/lakta/pkg/otel"
	pkg_workflows_temporal "github.com/Vilsol/lakta/pkg/workflows/temporal"
)

var defaultConfigs = []any{
	pkg_db_drivers_pgx.NewDefaultConfig(),
	pkg_grpc_client.NewDefaultConfig(),
	pkg_grpc_server.NewDefaultConfig(),
	pkg_health.NewDefaultConfig(),
	pkg_http_fiber.NewDefaultConfig(),
	pkg_logging_slog.NewDefaultConfig(),
	pkg_logging_tint.NewDefaultConfig(),
	pkg_otel.NewDefaultConfig(),
	pkg_workflows_temporal.NewDefaultConfig(),
}
