name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Build
        run: go build ./...

      - name: Test
        run: mise run test

      - name: Lint
        run: mise run lint

      - name: Vulnerability check
        run: mise run govulncheck

      - name: Doc check
        run: mise run doccheck
